config/routes.rb
Rails.application.routes.draw do
    
  
  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'employees/index'
  root to: 'employees#index'
  
  resources :departments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord

	has_many :users
	
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
  validates :contact, numericality: { only_integer: true }, allow_blank: true
  validates :contact, length: { is: 10 }, allow_blank: true

  belongs_to :department

  before_validation :assign_department, on: :create

  scope :search, ->(query_str) { where("name LIKE ?", "%#{query_str}%") }
  scope :filter_by, ->(department) { where('department_id = ?', department) }


  def full_name
    "#{first_name} #{last_name}".strip || email
  end

  private

  def assign_department
    self.department_id = 1#Department.first
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :archive)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = User.first 20
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  
  protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

  private

    def configure_permitted_parameters
      attributes = [ :first_name, :last_name, :email, :contact, :department_id,
        :password, :password_confirmation, :remember_me
      ]
      devise_parameter_sanitizer.permit :sign_up, keys: attributes
      devise_parameter_sanitizer.permit :account_update, keys: attributes
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def department_list
    Department.select("name, id")
  end

end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :archive %>
    <%= form.check_box :archive %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Archive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.archive %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Archive:</strong>
  <%= @department.archive %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Employees</h2>

<div class="table-settings mb-4 mt-4 mt-lg-0">
  <div class="row align-items-end">
    <div class="col-12 col-lg-6 d-flex">
      <div class="input-group me-2 me-lg-3">
        <span class="input-group-text"><span class="fas fa-search"></span></span>
        <input type="text" class="form-control" placeholder="Search" data-reflex="debounced:input->Employees#search" data-filter="<% @search_str %>" />
      </div>
      <select class="w-50 me-2 me-lg-3" data-controller="select" data-select-show-search-value="false" required data-reflex="change->Employees#filter" data-filter="<%=  @filter_by %>">
        <option selected value="">All</option>
        <% department_list.each do |dep| %> 
          <option value="<% dep.id %>"><%= dep.name.capitalize %></option>
        <% end %>
      </select>
    </div>
  </div>
</div>

<div data-controller="hello">
  <div class="btn btn-primary">Say Hello</div>
</div>

<div class="row">
  <div class="col-8">
    <div class="table-responsive">
      <table class= "table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>

        <tbody>
          <% if @employees.blank? %>
            <tr>
              <td colspan="2">No record found</td>
            </tr>
          <% else %>    
            <% @employees.each do |employee| %>
              <tr>
                <td><%= link_to employee.full_name, "#" %></td>
                <td><%= employee.email %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div> 
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Employees Mgmt", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Employees", root_path, class: "nav-link"%></li>
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Department", departments_path, class: "nav-link"%></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-capitalize" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.full_name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                <%= link_to "Setting", edit_user_registration_path, method: :get, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "nav-link"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Mgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="container pt-3">
      <%= yield %>
    </div> 
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if false#devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if false #devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if false#devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>